#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>

int main(int argc, char* argv[]) {
    if (argc != 3) {
        std::cerr << "Usage: embedder <src_dir> <dst_header>" << std::endl;
        return 1;
    }
    
    std::string src_dir = argv[1];
    std::string dst_file = argv[2];
    std::string src_file = src_dir + "/index.html";

    std::ifstream in(src_file, std::ios::binary);
    if (!in) {
        std::cerr << "Error: Could not open " << src_file << std::endl;
        return 1;
    }

    // Read file content
    std::vector<unsigned char> buffer(std::istreambuf_iterator<char>(in), {});

    std::ofstream out(dst_file);
    if (!out) {
        std::cerr << "Error: Could not write to " << dst_file << std::endl;
        return 1;
    }

    out << "#pragma once\n";
    out << "#include <cstddef>\n\n";
    out << "// Auto-generated by embedder tool. Do not edit.\n";
    out << "const unsigned char html_data[] = {\n";

    out << std::hex << std::setfill('0');
    for (size_t i = 0; i < buffer.size(); ++i) {
        out << "0x" << std::setw(2) << (int)buffer[i] << ",";
        if ((i + 1) % 16 == 0) out << "\n";
    }
    out << "\n};\n\n";
    out << "const size_t html_len = " << std::dec << buffer.size() << ";\n";
    
    std::cout << "Successfully embedded " << buffer.size() << " bytes." << std::endl;
    return 0;
}
